CREATE DATABASE  IF NOT EXISTS evgFlix;

USE evgFlix;

CREATE TABLE IF NOT EXISTS EvgFlix (
    id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    tipo CHAR(1) NOT NULL,
    CONSTRAINT pk_EvgFlix PRIMARY KEY (id),
    CONSTRAINT chk_tipo CHECK (tipo IN ('P', 'S'))
);

CREATE TABLE IF NOT EXISTS Recomendaciones (
    idEvg1 TINYINT UNSIGNED NOT NULL,
    idEvg2 TINYINT UNSIGNED NOT NULL,
    CONSTRAINT pk_Recomendaciones PRIMARY KEY (idEvg1, idEvg2),
    CONSTRAINT fk_Recomendaciones1 FOREIGN KEY (idEvg1) REFERENCES EvgFlix(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_Recomendaciones2 FOREIGN KEY (idEvg2) REFERENCES EvgFlix(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Pelicula (
    id TINYINT UNSIGNED NOT NULL,
    minutos_Adicionales SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT pk_Pelicula PRIMARY KEY (id),
    CONSTRAINT fk_Pelicula_EvgFlix FOREIGN KEY (id) REFERENCES EvgFlix(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Serie (
    id TINYINT UNSIGNED NOT NULL,
    CONSTRAINT pk_Serie PRIMARY KEY (id),
    CONSTRAINT fk_Serie_EvgFlix FOREIGN KEY (id) REFERENCES EvgFlix(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Temporada (
    id TINYINT UNSIGNED NOT NULL,
    numT SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT pk_Temporada PRIMARY KEY (id, numT),
    CONSTRAINT fk_Temporada_Serie FOREIGN KEY (id) REFERENCES Serie(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Episodios (
    id TINYINT UNSIGNED NOT NULL,
    numT SMALLINT UNSIGNED NOT NULL,
    numEp SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT pk_Episodios PRIMARY KEY (id, numT, numEp),
    CONSTRAINT fk_Episodios_Temporada FOREIGN KEY (id, numT) REFERENCES Temporada(id, numT)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
